kiosk/urls.py
from django.urls import path


from . import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('portal/', views.index, name='index'),
    path('sector/<int:sector_id>', views.projects, name='sector'),
    # ex: /polls/5/results/
    path('project/<int:project_id>', views.artifacts, name='project'),
    # ex: /polls/5/vote/
    path('artifact/<int:artifact_id>', views.artifact, name='artifact'),
]

tooba_kiosk/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('kiosk.urls')),
    path('admin/', admin.site.urls),
]

kiosk/models.py
from django.db import models
from django.utils import timezone


class Sector(models.Model):
    sector_text = models.CharField(max_length=200)
    img_url = models.CharField('image', max_length=200, blank="True")
    created_date = models.DateTimeField('publish time', default=timezone.now)


class DiscussionItem(models.Model):
    author = models.CharField(max_length=50)
    discussion_subject = models.CharField(max_length=1250, blank="True")
    discussion_text = models.CharField(max_length=2000)
    created_date = models.DateTimeField('publish time', default=timezone.now, blank="True")
    discussion_type = models.SmallIntegerField()
    discussion_id = models.IntegerField()


class Project(models.Model):
    project_text = models.CharField(max_length=200)
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
    img_url = models.CharField('image', max_length=200, blank="True")
    created_date = models.DateTimeField('publish time', default=timezone.now)


class Artifact(models.Model):
    artifact_text = models.CharField(max_length=200)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    file_url = models.CharField(max_length=200)
    file_type = models.CharField(max_length=4)
    created_date = models.DateTimeField('publish time', default=timezone.now)

class Announcements(models.Model):
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=500)
    date = models.DateTimeField('publish time', default=timezone.now)

kiosk/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from .models import *


def index(request):
    sector_list = Sector.objects.all()
    template = loader.get_template('kiosk/index.html')
    context = {'sectors': sector_list}
    return HttpResponse(template.render(context, request))


def landing(request):
    template = loader.get_template('kiosk/landing.html')
    context = {'announcements': Announcements.objects.first()}
    return HttpResponse(template.render(context, request))


def projects(request, sector_id):
    sector_name = Sector.objects.get(pk=sector_id).sector_text
    project_list = Project.objects.filter(sector=sector_id)
    return render(request, 'kiosk/sector.html', {'projects': project_list, 'sectorname': sector_name, 'sid': sector_id})


def artifacts(request, project_id):
    p = Project.objects.get(pk=project_id)
    project_name = p.project_text
    sector_name = p.sector.sector_text
    di = DiscussionItem.objects.filter(discussion_id=project_id)
    alist = Artifact.objects.filter(project=project_id)
    return render(request, 'kiosk/project.html',
                  {'artifacts': alist, 'projectname': project_name, 'sectorname': sector_name,
                   'sid': p.sector.id, 'pid': project_id, 'discussion': di})


def artifact(request, artifact_id):
    ar = Artifact.objects.get(pk=artifact_id)
    di = DiscussionItem.objects.filter(discussion_id=artifact_id, discussion_type=2)
    return render(request, 'kiosk/artifact.html',
                  {'artifact': ar, 'projectname': ar.project.project_text, 'sectorname': ar.project.sector.sector_text,
                   'discussion': di});

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="">
    <title>Tooba Kiosk</title>
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="{% static 'kiosk/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'kiosk/album.css' %}" rel="stylesheet">
    <link href="{% static 'kiosk/kiosk.css' %}" rel="stylesheet">
</head>

<body>

<header>

    <div class="navbar navbar-dark shadow-sm bg-toobalight">
        <div class="container d-flex justify-content-between">
            <a href="/portal/" class="navbar-brand d-flex align-items-center">
                <img class="tree" src="{% static 'kiosk/images/toobalogo.png' %}"/>
            </a>
            <div class="tbreadcrumb"><strong>{% block header %}{% endblock %}</strong></div>
            <a href="javascript:history.back()" class="navbar-brand d-flex align-items-center">
                <img  class="backbutton" src="{% static 'kiosk/images/backbutton.png' %}"/>
            </a>
        </div>
    </div>
</header>

<main role="main">
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</main>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'kiosk/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'kiosk/popper.min.js' %}"></script>
<script src="{% static 'kiosk/bootstrap.min.js' %}"></script>
<script src="{% static 'kiosk/holder.min.js' %}"></script>
<script src="{% static 'kiosk/kiosk.js' %}"></script>
</body>
</html>

templates/discussion.html
<div class="discussion col-md-4">
            <header>
                Project Summary
            </header>
            <article>
                {% for d in discussion %}
                    <div class="subject">{{ d.discussion_subject}}</div>
                    <p class="discuss">{{ d.discussion_text }}</p>
                    by <span class="author">{{d.author}}</span> @ <span class="time">{{ d.created_date }}</span>
                {% endfor %}
            </article>
        </div>

templates/kiosk/artifact.html
{% extends "base.html" %}
{% block header %}<span linkurl="/portal/">Tooba</span> >
    <span linkurl="{% url 'sector' artifact.project.sector.id %}">{{ sectorname }}</span> >
    <span linkurl="{% url 'project' artifact.project.id %}">{{ projectname }}</span> >
    {{ artifact.artifact_text }}{% endblock %}
{% block content %}
    <div class="col-md-7 arti-album">
        <div class="card mb-7 shadow-sm">
            <a href="javascript:alert('print');">
                <div class="card-body">
                    <img src="{{ artifact.file_url }}"/>
                    <div class="subtext">w/e</div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-md-1"></div>
    {% include "discussion.html" %}
{% endblock %}

templates/kiosk/index.html
{% extends "base.html" %}
{% block header %}
    Tooba
{% endblock %}
{% block content %}
    {% if sectors %}
        {% for sector in sectors %}
<div class="col-md-1 block{{ sector.id }}b breathe"></div>
            <div class="col-md-5 block{{ sector.id }}b breathe">
                <div class="card mb-4 shadow-sm">
                    <a href="{% url 'sector' sector.id %}">
                        <div class="card-body">
                            <div class="container">{{ sector.sector_text }}</div>
                            <div class="subtext">{{ sector.project_set.count }}</div>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No sectors.. Oh noes..</p>
    {% endif %}
{% endblock %}

templates/kiosk/landing.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="">
    <title>Tooba Kiosk</title>
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="{% static 'kiosk/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'kiosk/album.css' %}" rel="stylesheet">
    <link href="{% static 'kiosk/kiosk.css' %}" rel="stylesheet">
    <link href="{% static 'kiosk/pin.css' %}" rel="stylesheet">
</head>

<body class="landing">
<div id="prompt">
    <span class="">Enter PIN to Unlock</span>
</div>
<div class="invisible" id="pin">
  <div class="dots">
    <div class="dot"></div>
    <div class="dot"></div>
    <div class="dot"></div>
    <div class="dot"></div>
  </div>
  <p>Enter the password</p>
  <div class="numbers">
    <div class="number">1</div>
    <div class="number">2</div>
    <div class="number">3</div>
    <div class="number">4</div>
    <div class="number">5</div>
    <div class="number">6</div>
    <div class="number">7</div>
    <div class="number">8</div>
    <div class="number">9</div>
    <div class="number">0</div>
  </div>
</div>
</body>
<script src="{% static 'kiosk/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'kiosk/pin.js' %}"></script>
</html>

templates/kiosk/project.html
{% extends "base.html" %}
{% block header %}
    <span linkurl="/portal">Tooba</span> >
    <span linkurl="{% url 'sector' sid %}">{{ sectorname }}</span> >
    {{ projectname }}
{% endblock %}
{% block content %}
    {% if artifacts %}
        <div class="col-md-7">
            <div class="row">
                {% for artifact in artifacts %}
                <div class="col-md-3">
                    <div class="card mb-2 shadow-sm">
                        <a href="{% url 'artifact' artifact.id %}">
                            <div class="card-body">
                                <div class="whitey container">
                                    {{ artifact.artifact_text }} {{ artifact.filetype }}
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
        <div class="col-md-1">
        </div>
        {{ discussion.discussion_subject }}
        {% include "discussion.html" %}
    {% else %}
        <p>No projects.. Oh noes..</p>
    {% endif %}{% endblock %}

templates/kiosk/sector.html
{% extends "base.html" %}
{% block header %}
    <span linkurl="/portal">Tooba</span> >
    {{ sectorname }}{% endblock %}

{% block content %}
    {% if projects %}
        {% for project in projects %}
            <div class="col-md-2">
                <div class="card mb-2 shadow-sm">
                    <a href="{% url 'project' project.id %}">
                        <div class="card-body">
                            <div class="image"><img src="{{ project.img_url }}" /></div>
                            <div class="container">{{ project.project_text }}</div>
                            <div class="subtext"> ({{ project.artifact_set.count }})</div>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No sectors.. Oh noes..</p>
    {% endif %}{% endblock %}